// AUTO-GENERATED by scripts/gen_miniapp_cities.py — do not edit by hand.
// Source of truth: scripts/bot.py (_CITIES, _DISTRICTS_BY_CITY).

export interface CityLabels {
  he: string;
  ru: string;
  en: string;
}

export interface CityEntry {
  code: string;
  labels: CityLabels;
  districts: CityLabels[];
}

export interface CitiesData {
  cities: CityEntry[];
  fields: {
    numeric_range: string[];
    mamad_options: string[];
    quality_options: string[];
    required_choices: string[];
    deal_type_default: string;
  };
}

export const CITIES: CitiesData = {
  "cities": [
    {
      "code": "אשקלון",
      "labels": {
        "he": "אשקלון",
        "ru": "Ашкелон",
        "en": "Ashkelon"
      },
      "districts": [
        {
          "he": "אפרידר",
          "ru": "Афридар",
          "en": "Afridar"
        },
        {
          "he": "ברנע",
          "ru": "Барнеа",
          "en": "Barnea"
        },
        {
          "he": "עיר היין",
          "ru": "Ир ха-Яин",
          "en": "Ir HaYayin"
        },
        {
          "he": "מרינה",
          "ru": "Марина",
          "en": "Marina"
        },
        {
          "he": "אגמים",
          "ru": "Агамим",
          "en": "Agamim"
        },
        {
          "he": "נווה הדרים",
          "ru": "Неве ха-Дарим",
          "en": "Neve HaDarim"
        },
        {
          "he": "נווה אלונים",
          "ru": "Неве Алоним",
          "en": "Neve Alonim"
        },
        {
          "he": "הסיטי",
          "ru": "Сити",
          "en": "The City"
        },
        {
          "he": "גבעת ציון",
          "ru": "Гиват Цион",
          "en": "Givat Zion"
        },
        {
          "he": "שיקמים",
          "ru": "Шикмим",
          "en": "Shikmim"
        },
        {
          "he": "נווה ים",
          "ru": "Неве Ям",
          "en": "Neve Yam"
        },
        {
          "he": "נווה דקלים",
          "ru": "Неве Дкалим",
          "en": "Neve Dkalim"
        },
        {
          "he": "רמת בן גוריון",
          "ru": "Рамат Бен-Гурион",
          "en": "Ramat Ben Gurion"
        },
        {
          "he": "גולדה",
          "ru": "Голда",
          "en": "Golda"
        },
        {
          "he": "רמת אשכול",
          "ru": "Рамат Эшколь",
          "en": "Ramat Eshkol"
        },
        {
          "he": "עיר ימים",
          "ru": "Ир Ямим",
          "en": "Ir Yamim"
        },
        {
          "he": "נווה אילן",
          "ru": "Неве Илан",
          "en": "Neve Ilan"
        },
        {
          "he": "מגדל",
          "ru": "Мигдаль",
          "en": "Migdal"
        },
        {
          "he": "נאות אשקלון",
          "ru": "Ноот Ашкелон",
          "en": "Noot Ashkelon"
        },
        {
          "he": "בן גוריון",
          "ru": "Бен-Гурион",
          "en": "Ben Gurion"
        },
        {
          "he": "גן הורדים",
          "ru": "Ган ха-Врадим",
          "en": "Gan HaVradim"
        },
        {
          "he": "אגמים מזרח",
          "ru": "Агамим Мизрах",
          "en": "Agamim East"
        },
        {
          "he": "כוכב הצפון",
          "ru": "Кохав ха-Цафон",
          "en": "Kochav HaTzafon"
        },
        {
          "he": "ז'בוטינסקי",
          "ru": "Жаботински",
          "en": "Zhabotinsky"
        },
        {
          "he": "רמות אשקלון",
          "ru": "Рамот Ашкелон",
          "en": "Ramot Ashkelon"
        },
        {
          "he": "נוף ים",
          "ru": "Ноф Ям",
          "en": "Nof Yam"
        },
        {
          "he": "אשכולי פז",
          "ru": "Эшколей Паз",
          "en": "Eshkolei Paz"
        },
        {
          "he": "אזור התעשיה הקלה",
          "ru": "Пром. зона",
          "en": "Light Industrial Zone"
        }
      ]
    },
    {
      "code": "אשדוד",
      "labels": {
        "he": "אשדוד",
        "ru": "Ашдод",
        "en": "Ashdod"
      },
      "districts": [
        {
          "he": "רובע ט\"ו",
          "ru": "Рова 15 (Тет-Вав)",
          "en": "Rova 15"
        },
        {
          "he": "רובע ט'",
          "ru": "Рова 9 (Тет)",
          "en": "Rova 9"
        },
        {
          "he": "רובע א'",
          "ru": "Рова 1 (Алеф)",
          "en": "Rova 1"
        },
        {
          "he": "רובע י\"א",
          "ru": "Рова 11 (Юд-Алеф)",
          "en": "Rova 11"
        },
        {
          "he": "רובע י'",
          "ru": "Рова 10 (Юд)",
          "en": "Rova 10"
        },
        {
          "he": "רובע ה'",
          "ru": "Рова 5 (Хей)",
          "en": "Rova 5"
        },
        {
          "he": "רובע ג'",
          "ru": "Рова 3 (Гимель)",
          "en": "Rova 3"
        },
        {
          "he": "רובע ב'",
          "ru": "Рова 2 (Бет)",
          "en": "Rova 2"
        },
        {
          "he": "פארק עוגנים",
          "ru": "Парк Огнаим",
          "en": "Park Ogamim"
        },
        {
          "he": "רובע י\"ב",
          "ru": "Рова 12 (Юд-Бет)",
          "en": "Rova 12"
        },
        {
          "he": "רובע י\"ג",
          "ru": "Рова 13 (Юд-Гимель)",
          "en": "Rova 13"
        },
        {
          "he": "רובע ז'",
          "ru": "Рова 7 (Заин)",
          "en": "Rova 7"
        },
        {
          "he": "רובע ח'",
          "ru": "Рова 8 (Хет)",
          "en": "Rova 8"
        },
        {
          "he": "קרית איתנים",
          "ru": "Кирьят Эйтаним",
          "en": "Qiryat Eitanim"
        },
        {
          "he": "רובע י\"ז",
          "ru": "Рова 17 (Юд-Заин)",
          "en": "Rova 17"
        },
        {
          "he": "רובע י\"ד",
          "ru": "Рова 14 (Юд-Далет)",
          "en": "Rova 14"
        },
        {
          "he": "רובע ד'",
          "ru": "Рова 4 (Далет)",
          "en": "Rova 4"
        },
        {
          "he": "רובע ו'",
          "ru": "Рова 6 (Вав)",
          "en": "Rova 6"
        },
        {
          "he": "הקריה מע\"ר",
          "ru": "ха-Кирья (деловой центр)",
          "en": "HaKirya CBD"
        },
        {
          "he": "רובע הקריה",
          "ru": "Рова ха-Кирья",
          "en": "Rova HaKirya"
        },
        {
          "he": "עורף הנמל",
          "ru": "Ореф ха-Намаль",
          "en": "Port Hinterland"
        },
        {
          "he": "רובע ט\"ז",
          "ru": "Рова 16 (Тет-Заин)",
          "en": "Rova 16"
        },
        {
          "he": "קרית חלוצים",
          "ru": "Кирьят Халуцим",
          "en": "Qiryat Challutzim"
        },
        {
          "he": "בקמה",
          "ru": "Бкама",
          "en": "Bakama"
        },
        {
          "he": "מרינה",
          "ru": "Марина",
          "en": "Marina"
        }
      ]
    },
    {
      "code": "ירושלים",
      "labels": {
        "he": "ירושלים",
        "ru": "Иерусалим",
        "en": "Jerusalem"
      },
      "districts": [
        {
          "he": "בית חנינא",
          "ru": "Бейт Ханина",
          "en": "Beit Hanina"
        },
        {
          "he": "אום טובא",
          "ru": "Умм Туба",
          "en": "Umm Tuba"
        },
        {
          "he": "ערב א - סוואחרה",
          "ru": "Араб а-Савахре",
          "en": "Arab a-Sawahre"
        },
        {
          "he": "רמות",
          "ru": "Рамот",
          "en": "Ramot"
        },
        {
          "he": "א-טור",
          "ru": "А-Тур",
          "en": "At-Tur"
        },
        {
          "he": "פסגת זאב",
          "ru": "Писгат Зеэв",
          "en": "Pisgat Ze'ev"
        },
        {
          "he": "נחלת שבעה",
          "ru": "Нахалат Шива",
          "en": "Nahalat Shiva"
        },
        {
          "he": "מעלה הזיתים",
          "ru": "Маале ха-Зейтим",
          "en": "Maale HaZeitim"
        },
        {
          "he": "עיסוויה",
          "ru": "Иссавия",
          "en": "Isawiya"
        },
        {
          "he": "בית צפאפא",
          "ru": "Бейт Цафафа",
          "en": "Beit Safafa"
        },
        {
          "he": "שועפט",
          "ru": "Шуафат",
          "en": "Shuafat"
        },
        {
          "he": "גילה",
          "ru": "Гило",
          "en": "Gilo"
        },
        {
          "he": "הרובע המוסלמי",
          "ru": "Мусульманский квартал",
          "en": "Muslim Quarter"
        },
        {
          "he": "נוף ציון",
          "ru": "Ноф Цион",
          "en": "Nof Zion"
        },
        {
          "he": "מחנה יהודה - לב העיר",
          "ru": "Махане Йехуда – центр",
          "en": "Mahane Yehuda – City Center"
        },
        {
          "he": "בית הכרם",
          "ru": "Бейт ха-Керем",
          "en": "Beit HaKerem"
        },
        {
          "he": "אום א-שראיט",
          "ru": "Умм а-Шараит",
          "en": "Umm al-Sharayit"
        },
        {
          "he": "גבעת חנניה",
          "ru": "Гиват Хананья",
          "en": "Givat Hananya"
        },
        {
          "he": "ארנונה",
          "ru": "Арнона",
          "en": "Arnona"
        },
        {
          "he": "קרית היובל",
          "ru": "Кирьят ха-Йовель",
          "en": "Kiryat HaYovel"
        },
        {
          "he": "כפר שלמא - הכפר השוודי",
          "ru": "Кфар Шалем – Шведская деревня",
          "en": "Kfar Shalem – Swedish Village"
        },
        {
          "he": "גבעת שאול",
          "ru": "Гиват Шауль",
          "en": "Givat Shaul"
        },
        {
          "he": "הרובע היהודי",
          "ru": "Еврейский квартал",
          "en": "Jewish Quarter"
        },
        {
          "he": "ואדי ג'וז",
          "ru": "Вади Джоз",
          "en": "Wadi Joz"
        },
        {
          "he": "בית ישראל",
          "ru": "Бейт Исраэль",
          "en": "Beit Yisrael"
        },
        {
          "he": "מקור ברוך",
          "ru": "Макор Барух",
          "en": "Makor Baruch"
        },
        {
          "he": "בקעה",
          "ru": "Бака",
          "en": "Baka"
        },
        {
          "he": "קטמון הישנה",
          "ru": "Старый Катамон",
          "en": "Old Katamon"
        },
        {
          "he": "קטמונים",
          "ru": "Катамоним",
          "en": "Katamonim"
        },
        {
          "he": "חומת שמואל",
          "ru": "Хомат Шмуэль",
          "en": "Homat Shmuel"
        },
        {
          "he": "בית וגן",
          "ru": "Баит ве-Ган",
          "en": "Bayit VeGan"
        },
        {
          "he": "נחלאות",
          "ru": "Нахлаот",
          "en": "Nachlaot"
        },
        {
          "he": "נווה יעקב",
          "ru": "Неве Яаков",
          "en": "Neve Yaakov"
        },
        {
          "he": "רחביה",
          "ru": "Рехавия",
          "en": "Rehavia"
        },
        {
          "he": "כרם אברהם",
          "ru": "Керем Авраам",
          "en": "Kerem Avraham"
        },
        {
          "he": "ימין משה",
          "ru": "Йемин Моше",
          "en": "Yemin Moshe"
        },
        {
          "he": "טלביה",
          "ru": "Тальбия",
          "en": "Talbiya"
        },
        {
          "he": "רמת שלמה",
          "ru": "Рамат Шломо",
          "en": "Ramat Shlomo"
        },
        {
          "he": "קרית הלאום",
          "ru": "Кирьят ха-Леом",
          "en": "Kiryat HaLeom"
        },
        {
          "he": "באב א זהרה",
          "ru": "Баб а-Захара",
          "en": "Bab a-Zahara"
        },
        {
          "he": "ארמון הנציב",
          "ru": "Армон ха-Нацив",
          "en": "Armon HaNatziv"
        },
        {
          "he": "עמק רפאים",
          "ru": "Эмек Рефаим",
          "en": "Emek Refaim"
        },
        {
          "he": "גבעת הורדים",
          "ru": "Гиват ха-Врадим",
          "en": "Givat HaVradim"
        },
        {
          "he": "קרית מנחם",
          "ru": "Кирьят Менахем",
          "en": "Kiryat Menachem"
        },
        {
          "he": "מלחה",
          "ru": "Мальха",
          "en": "Malha"
        },
        {
          "he": "רוממה",
          "ru": "Ромема",
          "en": "Romema"
        },
        {
          "he": "מעלות דפנה",
          "ru": "Маалот Дафна",
          "en": "Maalot Dafna"
        },
        {
          "he": "קרית משה",
          "ru": "Кирьят Моше",
          "en": "Kiryat Moshe"
        },
        {
          "he": "תל ארזה",
          "ru": "Тель Арза",
          "en": "Tel Arza"
        },
        {
          "he": "רמת שרת",
          "ru": "Рамат Шарет",
          "en": "Ramat Sharett"
        },
        {
          "he": "סנהדריה",
          "ru": "Санхедрия",
          "en": "Sanhedria"
        },
        {
          "he": "הגבעה הצרפתית",
          "ru": "Французский холм",
          "en": "French Hill"
        },
        {
          "he": "רמת אשכול",
          "ru": "Рамат Эшколь",
          "en": "Ramat Eshkol"
        },
        {
          "he": "תלפיות תעשיה ומסחר",
          "ru": "Тальпиот пром.",
          "en": "Talpiot Industrial"
        },
        {
          "he": "הבוכרים",
          "ru": "Бухарский квартал",
          "en": "Bukharan Quarter"
        },
        {
          "he": "מאה שערים",
          "ru": "Меа Шеарим",
          "en": "Mea Shearim"
        },
        {
          "he": "הר נוף",
          "ru": "Хар Ноф",
          "en": "Har Nof"
        },
        {
          "he": "גבעת משואה",
          "ru": "Гиват Масуа",
          "en": "Givat Masua"
        },
        {
          "he": "אזור תעשיה עטרות",
          "ru": "Атарот пром.",
          "en": "Atarot Industrial"
        },
        {
          "he": "ממילא",
          "ru": "Мамила",
          "en": "Mamilla"
        },
        {
          "he": "מורשה",
          "ru": "Мораша",
          "en": "Morasha"
        },
        {
          "he": "קרית בעלז",
          "ru": "Кирьят Бельз",
          "en": "Kiryat Belz"
        },
        {
          "he": "גאולה",
          "ru": "Геула",
          "en": "Geula"
        },
        {
          "he": "המושבה היוונית",
          "ru": "Греческая колония",
          "en": "Greek Colony"
        },
        {
          "he": "ראס אל-עמוד",
          "ru": "Рас аль-Амуд",
          "en": "Ras al-Amud"
        },
        {
          "he": "הר הצופים",
          "ru": "Гора Скопус",
          "en": "Mount Scopus"
        },
        {
          "he": "קרית אונסדורף",
          "ru": "Кирьят Унсдорф",
          "en": "Kiryat Unsdorf"
        },
        {
          "he": "גבעת מרדכי",
          "ru": "Гиват Мордехай",
          "en": "Givat Mordechai"
        },
        {
          "he": "רמת דניה",
          "ru": "Рамат Дения",
          "en": "Ramat Denya"
        },
        {
          "he": "ניות",
          "ru": "Найот",
          "en": "Nayot"
        },
        {
          "he": "הר חוצבים",
          "ru": "Хар Хоцвим",
          "en": "Har Hotzvim"
        },
        {
          "he": "גבעת רם",
          "ru": "Гиват Рам",
          "en": "Givat Ram"
        },
        {
          "he": "הרובע הארמני",
          "ru": "Армянский квартал",
          "en": "Armenian Quarter"
        },
        {
          "he": "קרית שמואל",
          "ru": "Кирьят Шмуэль",
          "en": "Kiryat Shmuel"
        },
        {
          "he": "מחנה אלנבי",
          "ru": "Махане Алленби",
          "en": "Camp Allenby"
        },
        {
          "he": "גבעת המבתר",
          "ru": "Гиват ха-Мивтар",
          "en": "Givat HaMivtar"
        },
        {
          "he": "פת",
          "ru": "Пат",
          "en": "Pat"
        },
        {
          "he": "גבעת המטוס",
          "ru": "Гиват ха-Матос",
          "en": "Givat HaMatos"
        },
        {
          "he": "יד ושם",
          "ru": "Яд ва-Шем",
          "en": "Yad Vashem"
        },
        {
          "he": "מקור חיים",
          "ru": "Макор Хаим",
          "en": "Makor Haim"
        },
        {
          "he": "ליפתא",
          "ru": "Лифта",
          "en": "Lifta"
        },
        {
          "he": "יפה נוף",
          "ru": "Яфе Ноф",
          "en": "Yefe Nof"
        },
        {
          "he": "הולילנד",
          "ru": "Холиленд",
          "en": "Holyland"
        },
        {
          "he": "קרית מנחם בגין",
          "ru": "Кирьят Менахем Бегин",
          "en": "Kiryat Menachem Begin"
        },
        {
          "he": "שדה התעופה עטרות",
          "ru": "Аэропорт Атарот",
          "en": "Atarot Airport"
        },
        {
          "he": "ענתות",
          "ru": "Анатот",
          "en": "Anatot"
        }
      ]
    }
  ],
  "fields": {
    "numeric_range": [
      "rooms",
      "price",
      "sqm",
      "floor"
    ],
    "mamad_options": [
      "any",
      "required",
      "strict"
    ],
    "quality_options": [
      "exact",
      "partial"
    ],
    "required_choices": [
      "rooms",
      "price",
      "sqm",
      "floor",
      "district",
      "mamad"
    ],
    "deal_type_default": "rent_offer"
  }
};
